--Utiliser executeScript() pour mise à jour les données

DROP TABLE Produit CASCADE CONSTRAINTS;
DROP TABLE Client CASCADE CONSTRAINTS;
DROP TABLE Magasin CASCADE CONSTRAINTS;
DROP TABLE TypesDeProfil CASCADE CONSTRAINTS;
DROP TABLE Commande CASCADE CONSTRAINTS;
DROP TABLE Preferer CASCADE CONSTRAINTS;
DROP TABLE Stocker CASCADE CONSTRAINTS;
DROP TABLE Appartenir_Type CASCADE CONSTRAINTS;
DROP TABLE Delivrer CASCADE CONSTRAINTS;
DROP TABLE Repartir CASCADE CONSTRAINTS;
DROP TABLE Composer CASCADE CONSTRAINTS;
DROP TABLE Correspondre CASCADE CONSTRAINTS;



-- Table Produit
CREATE TABLE Produit (
ProduitId VARCHAR(50) PRIMARY KEY,
NomProd VARCHAR(100) NOT NULL,
PrixAuKg DECIMAL(10, 2) NULL,
PrixUnitaire DECIMAL(10, 2),
Poids DECIMAL(10, 2) NULL,
Nutriscore CHAR(1) NOT NULL CHECK (Nutriscore IN ('A', 'B', 'C', 'D', 'E', ' ')),
Categorie VARCHAR(50) NOT NULL,
Marque VARCHAR(50) NOT NULL,
Bio VARCHAR2(5) CHECK (Bio IN ('TRUE', 'FALSE'))
);
-- Table Client
CREATE TABLE Client (
ClientId VARCHAR(50) PRIMARY KEY,
Nom VARCHAR(100) NOT NULL,
Prenom VARCHAR(100) NOT NULL,
Age INT NOT NULL,
Sexe CHAR(1) NOT NULL CHECK (Sexe IN ('M', 'F', 'O')),
Adresse VARCHAR(200) NOT NULL
);
-- Table Magasin
CREATE TABLE Magasin (
MagId INT PRIMARY KEY,
NomMag VARCHAR(100) NOT NULL,
AdresseMag VARCHAR(200) NOT NULL,
CodePostalMag CHAR(5) NOT NULL,
VilleMag VARCHAR(100) NOT NULL
);
-- Table TypesDeProfil
CREATE TABLE TypesDeProfil (
ProfilId INT PRIMARY KEY ,
NomProfil VARCHAR(50) NOT NULL
);
-- Table Commande
CREATE TABLE Commande (
CommandeId NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
DateCommande DATE NOT NULL,
MagId INT NOT NULL,
ClientId VARCHAR(50) NOT NULL,
EtatCom VARCHAR(50) NOT NULL CHECK (EtatCom IN ('En preparation', 'En attente de livraison','Finalisee')),
CONSTRAINT FK_Commande_Magasin FOREIGN KEY (MagId) REFERENCES Magasin(MagId),
CONSTRAINT FK_Commande_Client FOREIGN KEY (ClientId) REFERENCES Client(ClientId)
);
-- Table Preferer
CREATE TABLE Preferer (
ProduitId VARCHAR(50) NOT NULL,
ClientId VARCHAR(50) NOT NULL,
PRIMARY KEY (ProduitId, ClientId),
CONSTRAINT FK_Preferer_Produit FOREIGN KEY (ProduitId) REFERENCES Produit(ProduitId),
CONSTRAINT FK_Preferer_Client FOREIGN KEY (ClientId) REFERENCES Client(ClientId)
);
-- Table Stocker
CREATE TABLE Stocker (
ProduitId VARCHAR(50) NOT NULL,
MagId INT NOT NULL,
QteStock INT NOT NULL,
PRIMARY KEY (ProduitId, MagId),
CONSTRAINT FK_Stocker_Produit FOREIGN KEY (ProduitId) REFERENCES Produit(ProduitId),
CONSTRAINT FK_Stocker_Magasin FOREIGN KEY (MagId) REFERENCES Magasin(MagId)
);
-- Table Appartenir_Type
CREATE TABLE Appartenir_Type (
ClientId VARCHAR(50) NOT NULL,
ProfilId INT NOT NULL,
PRIMARY KEY (ClientId, ProfilId),
CONSTRAINT FK_Appartenir_Type_Client FOREIGN KEY (ClientId) REFERENCES Client(ClientId),
CONSTRAINT FK_Appartenir_Type_Profil FOREIGN KEY (ProfilId) REFERENCES TypesDeProfil(ProfilId)
);
-- Table Delivrer
CREATE TABLE Delivrer (
ProduitId VARCHAR(50) NOT NULL,
CommandeId NUMBER NOT NULL,
QuantiteLivraison INT NOT NULL,
ModeLivraison VARCHAR(50) NOT NULL,
DateLivraison DATE NOT NULL,
PRIMARY KEY (ProduitId, CommandeId),
CONSTRAINT FK_Delivrer_Produit FOREIGN KEY (ProduitId) REFERENCES Produit(ProduitId),
CONSTRAINT FK_Delivrer_Commande FOREIGN KEY (CommandeId) REFERENCES Commande(CommandeId)
);
-- Table Repartir
CREATE TABLE Repartir (
ProduitId VARCHAR(50) NOT NULL,
CommandeId NUMBER NOT NULL,
MagId INT NOT NULL,
QteRep INT NOT NULL,
PRIMARY KEY (ProduitId, CommandeId, MagId),
CONSTRAINT FK_Repartir_Produit FOREIGN KEY (ProduitId) REFERENCES Produit(ProduitId),
CONSTRAINT FK_Repartir_Commande FOREIGN KEY (CommandeId) REFERENCES Commande(CommandeId),
CONSTRAINT FK_Repartir_Magasin FOREIGN KEY (MagId) REFERENCES Magasin(MagId)
);
-- Table Composer
CREATE TABLE Composer (
ProduitId VARCHAR(50) NOT NULL,
CommandeId NUMBER NOT NULL,
QteCom INT NOT NULL,
PRIMARY KEY (ProduitId, CommandeId),
CONSTRAINT FK_Composer_Produit FOREIGN KEY (ProduitId) REFERENCES Produit(ProduitId),
CONSTRAINT FK_Composer_Commande FOREIGN KEY (CommandeId) REFERENCES Commande(CommandeId)
);
-- Table Correspondre
CREATE TABLE Correspondre (
ProduitId VARCHAR(50) NOT NULL,
ProfilId INT NOT NULL,
PRIMARY KEY (ProduitId, ProfilId),
CONSTRAINT FK_Correspondre_Produit FOREIGN KEY (ProduitId) REFERENCES Produit(ProduitId),
CONSTRAINT FK_Correspondre_Profil FOREIGN KEY (ProfilId) REFERENCES TypesDeProfil(ProfilId)
);


-- Table Produit
INSERT ALL

		INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (1, 'Spaghetti', NULL, 1.50, 500, 'B', 'Pâtes', 'Panzani', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (2, 'Piles AA', NULL, 4.99, NULL, ' ', 'Électronique', 'Duracell', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (3, 'Couches Bébé Taille 3', NULL, 18.99, NULL, ' ', 'Hygiène', 'Pampers', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (4, 'Sauce Ketchup', 3.98, 2.50, 750, 'C', 'Condiments', 'Heinz', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (5, 'Saumon Fumé', 35.00, NULL, 200, 'B', 'Poisson', 'Labeyrie', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (6, 'Banane', 1.50, NULL, 120, 'A', 'Fruits', 'Chiquita', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (7, 'Pomme', 2.20, NULL, 150, 'A', 'Fruits', 'Pink Lady', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (8, 'Liquide Vaisselle', NULL, 2.75, NULL, ' ', 'Entretien', 'Paic', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (9, 'Yaourt Nature', NULL, 2.99, 500, 'A', 'Produits Laitiers', 'Danone', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (10, 'Eau Minérale 1L', NULL, 0.60, 1000, 'A', 'Boissons', 'Evian', 'FALSE')   
   
   

    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (11, 'Céréales Chocolatées', NULL, 4.50, 500, 'C', 'Petit-Déjeuner', 'Kellogg''s', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (12, 'Poulet Rôti', 8.50, NULL, 1000, 'C', 'Viandes', 'Le Gaulois', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (13, 'Pain de Mie', NULL, 1.85, 500, 'B', 'Boulangerie', 'Harry''s', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (14, 'Beurre Demi-Sel', NULL, 2.30, 250, 'A', 'Produits Laitiers', 'Président', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (15, 'Fromage Râpé', NULL, 3.40, 200, 'B', 'Produits Laitiers', 'Emmental', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (16, 'Pizza Margherita', NULL, 4.99, 400, 'D', 'Plats Préparés', 'Buitoni', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (17, 'Chips Nature', NULL, 1.80, 200, 'C', 'Snacks', 'Lay''s', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (18, 'Lait UHT 1L', NULL, 0.95, 1000, 'A', 'Produits Laitiers', 'Candia', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (19, 'Oeufs x12', NULL, 3.20, NULL, 'A', 'Produits Frais', 'Matines', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (20, 'Riz Basmati', NULL, 2.75, 1000, 'A', 'Céréales', 'Taureau Ailé', 'TRUE')


    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (21, 'Farine de Blé', NULL, 1.20, 1000, 'A', 'Épicerie', 'Francine', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (22, 'Jambon Blanc', 12.00, NULL, 150, 'B', 'Charcuterie', 'Herta', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (23, 'Crème Fraîche', NULL, 2.50, 200, 'B', 'Produits Laitiers', 'Elle et Vire', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (24, 'Lentilles Vertes', NULL, 2.10, 500, 'A', 'Céréales', 'Celnat', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (25, 'Sucre en Poudre', NULL, 1.50, 1000, 'C', 'Épicerie', 'Daddy', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (26, 'Chocolat Noir', NULL, 2.99, 200, 'B', 'Snacks', 'Lindt', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (27, 'Huile d Olive', NULL, 5.99, 750, 'A', 'Condiments', 'Puget', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (28, 'Cornichons', NULL, 2.75, 400, 'A', 'Condiments', 'Amora', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (29, 'Thé Vert', NULL, 3.99, NULL, 'A', 'Boissons', 'Lipton', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (30, 'Yaourt aux Fruits', NULL, 3.50, 500, 'B', 'Produits Laitiers', 'Activia', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (31, 'Glace à la Vanille', NULL, 4.50, 500, 'C', 'Glaces', 'Magnum', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (32, 'Moutarde', NULL, 1.50, 200, 'A', 'Condiments', 'Dijon', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (33, 'Chocolat au Lait', NULL, 2.20, 150, 'B', 'Snacks', 'Milka', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (34, 'Confiture de Fraises', NULL, 3.99, 370, 'B', 'Épicerie', 'Bonne Maman', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (35, 'Purée de Pommes de Terre', NULL, 2.50, 400, 'C', 'Plats Préparés', 'Cassegrain', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (36, 'Café Moulu', NULL, 3.60, 250, 'A', 'Boissons', 'Carte Noire', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (37, 'Légumes Surgelés', NULL, 2.80, 500, 'A', 'Surgelés', 'Picard', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (38, 'Yaourt Grec', NULL, 1.80, 200, 'A', 'Produits Laitiers', 'Fage', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (39, 'Ail en Gousse', NULL, 0.60, 100, 'A', 'Épicerie', 'Ducros', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (40, 'Vinaigre Balsamique', NULL, 3.40, 500, 'A', 'Condiments', 'Cucina', 'TRUE')
    
    
	INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (41, 'Pâtes de Riz', NULL, 2.60, 300, 'A', 'Pâtes', 'Sabarot', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (42, 'Conserves de Thon', NULL, 2.80, 200, 'C', 'Conserves', 'Charles et Alice', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (43, 'Crème Caramel', NULL, 1.80, 150, 'B', 'Desserts', 'Bonne Maman', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (44, 'Bière Blonde', NULL, 2.50, 500, 'D', 'Boissons', 'Heineken', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (45, 'Chocolat au Lait Praliné', NULL, 3.20, 200, 'C', 'Snacks', 'Lindt', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (46, 'Gel Douche', NULL, 3.20, 300, ' ', 'Hygiène', 'Dove', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (47, 'Pommes de Terre', 0.95, NULL, 2000, 'A', 'Légumes', 'Agriculteurs Locaux', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (48, 'Epinards Surgelés', NULL, 2.10, 1000, 'A', 'Surgelés', 'Bonduelle', 'TRUE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (49, 'Saucisses de Francfort', 9.00, NULL, 300, 'C', 'Charcuterie', 'Herta', 'FALSE')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque, Bio) VALUES (50, 'Coca-Cola 1.5L', NULL, 1.50, 1500, 'D', 'Boissons', 'Coca-Cola', 'FALSE')
    
    --Jeu de donées pour les pates
    
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (51, 'Tagliatelles', NULL, 1.80, 500, 'A', 'Pâtes', 'Barilla')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (52, 'Penne Rigate', NULL, 1.40, 400, 'B', 'Pâtes', 'De Cecco')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (53, 'Coquillettes', NULL, 1.20, 300, 'C', 'Pâtes', 'Panzani')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (54, 'Fusilli', NULL, 1.50, 500, 'B', 'Pâtes', 'Rummo')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (55, 'Torsades', NULL, 1.60, 400, 'A', 'Pâtes', 'Barilla')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (56, 'Lasagnes', NULL, 2.00, 300, 'C', 'Pâtes', 'Panzani')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (57, 'Ravioles', NULL, 2.50, 250, 'B', 'Pâtes', 'Giovanni Rana')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (58, 'Coudes', NULL, 1.30, 500, 'A', 'Pâtes', 'Lustucru')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (59, 'Macaroni', NULL, 1.70, 450, 'B', 'Pâtes', 'Barilla')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (60, 'Farfalle', NULL, 1.60, 500, 'A', 'Pâtes', 'De Cecco')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (61, 'Spaghetti Intégrales', NULL, 2.00, 400, 'A', 'Pâtes', 'Rummo')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (62, 'Orecchiette', NULL, 1.90, 350, 'B', 'Pâtes', 'Panzani')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (63, 'Linguine', NULL, 1.80, 450, 'B', 'Pâtes', 'Barilla')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (64, 'Vermicelles', NULL, 1.40, 300, 'C', 'Pâtes', 'Lustucru')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (65, 'Rigatoni', NULL, 1.50, 500, 'A', 'Pâtes', 'De Cecco')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (66, 'Cannelloni', NULL, 2.20, 400, 'B', 'Pâtes', 'Rummo')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (67, 'Capellini', NULL, 1.80, 350, 'A', 'Pâtes', 'Barilla')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (68, 'Fusilli Intégrales', NULL, 2.10, 400, 'A', 'Pâtes', 'Giovanni Rana')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (69, 'Spaghettini', NULL, 1.70, 450, 'B', 'Pâtes', 'De Cecco')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (70, 'Pâtes Aux Légumes', NULL, 2.50, 300, 'A', 'Pâtes', 'Panzani')
    
    --jeu de donénes pour les fruits
    
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (71, 'Pommes Golden', 2.50, NULL, 1000, 'A', 'Fruits', 'BioVerde')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (72, 'Bananes', 1.80, NULL, 1200, 'A', 'Fruits', 'TropiFruit')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (73, 'Oranges', 2.20, NULL, 1500, 'A', 'Fruits', 'CitrusJoy')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (74, 'Poires Conférence', 2.70, NULL, 1000, 'A', 'Fruits', 'FruitéBio')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (75, 'Kiwis', 3.20, NULL, 500, 'A', 'Fruits', 'GreenZest')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (76, 'Raisins Rouges', 4.00, NULL, 1000, 'A', 'Fruits', 'SunnyVine')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (77, 'Fraises Gariguette', 5.00, NULL, 250, 'A', 'Fruits', 'BerryFresh')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (78, 'Pastèque', 1.50, NULL, 5000, 'A', 'Fruits', 'Tropical')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (79, 'Melon Charentais', 3.00, NULL, 1500, 'A', 'Fruits', 'SummerSweet')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (80, 'Abricots', 4.20, NULL, 1000, 'A', 'Fruits', 'FruitLover')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (81, 'Cerises', 6.50, NULL, 500, 'A', 'Fruits', 'CherryDelight')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (82, 'Pêches Jaunes', 3.80, NULL, 1000, 'A', 'Fruits', 'SunshineFruit')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (83, 'Mangues', 2.50, NULL, 800, 'A', 'Fruits', 'TropiFruit')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (84, 'Ananas', 3.50, NULL, 1500, 'A', 'Fruits', 'ExoticJoy')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (85, 'Framboises', 7.00, NULL, 250, 'A', 'Fruits', 'BerryFresh')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (86, 'Myrtilles', 8.00, NULL, 250, 'A', 'Fruits', 'BlueBerryLand')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (87, 'Prunes', 3.00, NULL, 1000, 'A', 'Fruits', 'PlumPerfect')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (88, 'Pomelos', 2.80, NULL, 1200, 'A', 'Fruits', 'CitrusJoy')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (89, 'Citrons Jaunes', 2.20, NULL, 1000, 'A', 'Fruits', 'BioVerde')
    INTO Produit (ProduitId, NomProd, PrixAuKg, PrixUnitaire, Poids, Nutriscore, Categorie, Marque) VALUES (90, 'Figues', 5.50, NULL, 500, 'A', 'Fruits', 'MediterraneanDelight')

SELECT * FROM dual;


-- Table Client
INSERT ALL
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('1', 'Dupont', 'Jean', 34, 'M', '12 Rue des Lilas, Paris')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('2', 'Martin', 'Marie', 28, 'F', '25 Avenue des Fleurs, Lyon')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('3', 'Bernard', 'Luc', 45, 'M', '7 Rue de la Paix, Marseille')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('4', 'Durand', 'Sophie', 39, 'F', '16 Boulevard Haussmann, Paris')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('5', 'Moreau', 'Paul', 52, 'M', '10 Rue des Champs, Toulouse')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('6', 'Petit', 'Chloé', 22, 'F', '18 Rue de la Liberté, Bordeaux')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('7', 'Lemoine', 'Julien', 31, 'M', '8 Rue des Violettes, Nantes')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('8', 'Girard', 'Emma', 26, 'F', '11 Avenue des Acacias, Lille')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('9', 'Roux', 'Antoine', 47, 'M', '14 Rue des Écoles, Strasbourg')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('10', 'Blanc', 'Alice', 30, 'F', '20 Allée des Tilleuls, Rennes')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('11', 'Gauthier', 'Nicolas', 40, 'M', '22 Rue des Bouleaux, Montpellier')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('12', 'Perrin', 'Camille', 33, 'F', '5 Rue des Peupliers, Dijon')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('13', 'Fernandez', 'Hugo', 29, 'M', '13 Rue des Rosiers, Orléans')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('14', 'Lopez', 'Manon', 25, 'F', '19 Rue des Pommiers, Metz')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('15', 'David', 'Louis', 50, 'M', '30 Rue des Platanes, Tours')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('16', 'Fontaine', 'Sarah', 38, 'F', '21 Rue des Tilleuls, Clermont-Ferrand')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('17', 'Chevalier', 'Thomas', 42, 'M', '12 Rue des Érables, Grenoble')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('18', 'Clement', 'Laura', 27, 'F', '24 Rue des Lilas, Nice')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('19', 'Renaud', 'Éric', 48, 'M', '9 Avenue des Chênes, Rouen')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('20', 'Dumont', 'Élise', 32, 'F', '6 Rue des Pins, Nancy')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('21', 'Lemoine', 'Patrick', 36, 'M', '17 Boulevard des Ormes, Amiens')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('22', 'Gonzalez', 'Isabelle', 41, 'F', '18 Rue des Vignes, Le Havre')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('23', 'Bertrand', 'Jacques', 55, 'M', '3 Allée des Marronniers, Saint-Étienne')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('24', 'Morel', 'Clara', 21, 'F', '26 Rue des Peupliers, Brest')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('25', 'Vidal', 'Lucas', 28, 'M', '28 Avenue des Érables, Toulon')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('26', 'Rolland', 'Sophie', 30, 'F', '15 Rue des Châtaigniers, Reims')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('27', 'Leclerc', 'Simon', 45, 'M', '4 Rue des Orangers, Perpignan')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('28', 'Aubert', 'Lucie', 37, 'F', '8 Allée des Cyprès, Limoges')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('29', 'Dupuy', 'Gabriel', 52, 'M', '10 Rue des Cèdres, Angers')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('30', 'Fabre', 'Elodie', 24, 'F', '13 Boulevard des Sapins, Nîmes')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('31', 'Pascal', 'Alexandre', 29, 'M', '19 Rue des Peupliers, Grenoble')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('32', 'Bonnet', 'Julie', 35, 'F', '9 Avenue des Platanes, Rennes')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('33', 'Charpentier', 'Adrien', 40, 'M', '23 Boulevard des Lilas, Caen')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('34', 'Renard', 'Margaux', 26, 'F', '14 Rue des Violettes, Montpellier')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('35', 'Colin', 'Baptiste', 44, 'M', '7 Avenue des Fleurs, Bordeaux')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('36', 'Faure', 'Alice', 27, 'F', '16 Rue des Oliviers, Strasbourg')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('37', 'Masson', 'Étienne', 39, 'M', '20 Boulevard des Églantiers, Lyon')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('38', 'Dufour', 'Anaïs', 23, 'F', '22 Rue des Acacias, Marseille')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('39', 'Benoit', 'Quentin', 46, 'M', '11 Avenue des Peupliers, Toulouse')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('40', 'Perrot', 'Noémie', 31, 'F', '26 Rue des Rosiers, Paris')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('41', 'Marchand', 'Victor', 32, 'M', '18 Rue des Chênes, Nantes')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('42', 'Aubry', 'Emma', 24, 'F', '6 Rue des Tilleuls, Nice')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('43', 'Gregoire', 'Thomas', 53, 'M', '14 Boulevard des Érables, Amiens')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('44', 'Langlois', 'Alice', 29, 'F', '19 Rue des Cyprès, Orléans')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('45', 'Pichon', 'Raphael', 34, 'M', '8 Allée des Marronniers, Metz')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('46', 'Barbier', 'Elisa', 40, 'F', '3 Rue des Platanes, Saint-Étienne')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('47', 'Boulanger', 'Arthur', 37, 'M', '22 Avenue des Érables, Brest')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('48', 'Hamon', 'Camille', 26, 'F', '9 Boulevard des Châtaigniers, Toulon')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('49', 'Clément', 'Romain', 41, 'M', '5 Rue des Orangers, Reims')
    INTO Client (ClientId, Nom, Prenom, Age, Sexe, Adresse) VALUES ('50', 'Charrier', 'Lea', 33, 'F', '17 Boulevard des Sapins, Perpignan')
SELECT * FROM dual;


-- Table Magasin
INSERT ALL
    INTO Magasin (MagId, NomMag, AdresseMag, CodePostalMag, VilleMag) VALUES (1, 'Interprix Centre', '10 Rue Alsace Lorraine', '31000', 'Toulouse')
    INTO Magasin (MagId, NomMag, AdresseMag, CodePostalMag, VilleMag) VALUES (2, 'Interprix Jean Rieux', '15 Avenue Jean Rieux', '31400', 'Toulouse')
    INTO Magasin (MagId, NomMag, AdresseMag, CodePostalMag, VilleMag) VALUES (3, 'Interprix Gramont', '20 Boulevard Pierre Semard', '31200', 'Toulouse')
    INTO Magasin (MagId, NomMag, AdresseMag, CodePostalMag, VilleMag) VALUES (4, 'Interprix Côte Pavée', '30 Rue de la Côte Pavée', '31500', 'Toulouse')
    INTO Magasin (MagId, NomMag, AdresseMag, CodePostalMag, VilleMag) VALUES (5, 'Interprix Minimes', '45 Rue des Minimes', '31200', 'Toulouse')
    INTO Magasin (MagId, NomMag, AdresseMag, CodePostalMag, VilleMag) VALUES (6, 'Interprix Capitole', '5 Place du Capitole', '31000', 'Toulouse')
    INTO Magasin (MagId, NomMag, AdresseMag, CodePostalMag, VilleMag) VALUES (7, 'Interprix Patte d Oie', '12 Allée de Barcelone', '31300', 'Toulouse')
    INTO Magasin (MagId, NomMag, AdresseMag, CodePostalMag, VilleMag) VALUES (8, 'Interprix Croix Daurade', '50 Avenue Croix Daurade', '31200', 'Toulouse')
    INTO Magasin (MagId, NomMag, AdresseMag, CodePostalMag, VilleMag) VALUES (9, 'Interprix Purpan', '25 Rue de Purpan', '31300', 'Toulouse')
    INTO Magasin (MagId, NomMag, AdresseMag, CodePostalMag, VilleMag) VALUES (10, 'Interprix Saint Cyprien', '8 Place Saint Cyprien', '31300', 'Toulouse')
SELECT * FROM dual;


-- Table Commande
INSERT INTO Commande (DateCommande, MagId, ClientId, EtatCom)
SELECT TO_DATE('2025-01-01', 'YYYY-MM-DD'), 1, '1', 'En preparation' FROM dual
UNION ALL
SELECT TO_DATE('2025-01-02', 'YYYY-MM-DD'), 2, '2', 'En preparation' FROM dual
UNION ALL
SELECT TO_DATE('2025-05-02', 'YYYY-MM-DD'), 3, '3', 'En preparation' FROM dual
UNION ALL
SELECT TO_DATE('2025-01-03', 'YYYY-MM-DD'), 1, '25', 'En attente de livraison' FROM dual
UNION ALL
SELECT TO_DATE('2025-01-04', 'YYYY-MM-DD'), 2, '18', 'Finalisee' FROM dual
UNION ALL
SELECT TO_DATE('2025-01-05', 'YYYY-MM-DD'), 3, '12', 'En preparation' FROM dual
UNION ALL
SELECT TO_DATE('2025-01-06', 'YYYY-MM-DD'), 4, '37', 'En attente de livraison' FROM dual
UNION ALL
SELECT TO_DATE('2025-01-07', 'YYYY-MM-DD'), 5, '1', 'Finalisee' FROM dual
UNION ALL
SELECT TO_DATE('2025-01-08', 'YYYY-MM-DD'), 6, '9', 'En preparation' FROM dual
UNION ALL
SELECT TO_DATE('2025-01-09', 'YYYY-MM-DD'), 7, '50', 'Finalisee' FROM dual
UNION ALL
SELECT TO_DATE('2025-01-10', 'YYYY-MM-DD'), 8, '3', 'En attente de livraison' FROM dual
UNION ALL
SELECT TO_DATE('2025-01-11', 'YYYY-MM-DD'), 9, '21', 'En preparation' FROM dual
UNION ALL
SELECT TO_DATE('2025-01-12', 'YYYY-MM-DD'), 10, '14', 'Finalisee' FROM dual
UNION ALL
SELECT TO_DATE('2025-01-13', 'YYYY-MM-DD'), 1, '26', 'En attente de livraison' FROM dual
UNION ALL
SELECT TO_DATE('2025-01-14', 'YYYY-MM-DD'), 2, '7', 'Finalisee' FROM dual
UNION ALL
SELECT TO_DATE('2025-01-15', 'YYYY-MM-DD'), 3, '34', 'En preparation' FROM dual
UNION ALL
SELECT TO_DATE('2024-01-15', 'YYYY-MM-DD'), 1, '5', 'En attente de livraison' FROM dual
UNION ALL
SELECT TO_DATE('2024-02-20', 'YYYY-MM-DD'), 2, '12', 'Finalisee' FROM dual
UNION ALL
SELECT TO_DATE('2024-03-10', 'YYYY-MM-DD'), 3, '30', 'En preparation' FROM dual
UNION ALL
SELECT TO_DATE('2024-04-25', 'YYYY-MM-DD'), 4, '7', 'Finalisee' FROM dual
UNION ALL
SELECT TO_DATE('2024-05-05', 'YYYY-MM-DD'), 5, '22', 'En attente de livraison' FROM dual
UNION ALL
SELECT TO_DATE('2024-06-12', 'YYYY-MM-DD'), 6, '9', 'En preparation' FROM dual
UNION ALL
SELECT TO_DATE('2024-07-01', 'YYYY-MM-DD'), 7, '15', 'Finalisee' FROM dual
UNION ALL
SELECT TO_DATE('2024-08-18', 'YYYY-MM-DD'), 8, '29', 'En attente de livraison' FROM dual
UNION ALL
SELECT TO_DATE('2024-09-05', 'YYYY-MM-DD'), 9, '3', 'En preparation' FROM dual
UNION ALL
SELECT TO_DATE('2024-10-30', 'YYYY-MM-DD'), 10, '11', 'Finalisee' FROM dual
UNION ALL
SELECT TO_DATE('2024-11-15', 'YYYY-MM-DD'), 1, '18', 'En attente de livraison' FROM dual
UNION ALL
SELECT TO_DATE('2024-12-01', 'YYYY-MM-DD'), 2, '34', 'En preparation' FROM dual
UNION ALL
SELECT TO_DATE('2024-12-20', 'YYYY-MM-DD'), 3, '8', 'Finalisee' FROM dual
UNION ALL
SELECT TO_DATE('2025-01-02', 'YYYY-MM-DD'), 4, '20', 'En attente de livraison' FROM dual
UNION ALL
SELECT TO_DATE('2025-01-06', 'YYYY-MM-DD'), 5, '45', 'En preparation' FROM dual
UNION ALL
SELECT TO_DATE('2025-01-08', 'YYYY-MM-DD'), 6, '27', 'Finalisee' FROM dual
UNION ALL
SELECT TO_DATE('2025-01-09', 'YYYY-MM-DD'), 7, '39', 'En attente de livraison' FROM dual
UNION ALL
SELECT TO_DATE('2024-03-17', 'YYYY-MM-DD'), 8, '13', 'En preparation' FROM dual
UNION ALL
SELECT TO_DATE('2024-05-25', 'YYYY-MM-DD'), 9, '21', 'Finalisee' FROM dual
UNION ALL
SELECT TO_DATE('2024-07-14', 'YYYY-MM-DD'), 10, '40', 'En attente de livraison' FROM dual;



-- Table Composer
INSERT ALL
    INTO Composer (ProduitId, CommandeId, QteCom) VALUES ('1', (SELECT CommandeId FROM Commande WHERE CommandeId = 1), 3)
    INTO Composer (ProduitId, CommandeId, QteCom) VALUES ('2', (SELECT CommandeId FROM Commande WHERE CommandeId = 1), 2)
    INTO Composer (ProduitId, CommandeId, QteCom) VALUES ('3', (SELECT CommandeId FROM Commande WHERE CommandeId = 1), 4)
    INTO Composer (ProduitId, CommandeId, QteCom) VALUES ('4', (SELECT CommandeId FROM Commande WHERE CommandeId = 1), 1)

    INTO Composer (ProduitId, CommandeId, QteCom) VALUES ('1', (SELECT CommandeId FROM Commande WHERE CommandeId = 2), 2)
    INTO Composer (ProduitId, CommandeId, QteCom) VALUES ('2', (SELECT CommandeId FROM Commande WHERE CommandeId = 2), 5)
    INTO Composer (ProduitId, CommandeId, QteCom) VALUES ('3', (SELECT CommandeId FROM Commande WHERE CommandeId = 2), 2)
    INTO Composer (ProduitId, CommandeId, QteCom) VALUES ('4', (SELECT CommandeId FROM Commande WHERE CommandeId = 2), 3)
SELECT * FROM dual;



-- Table TypesDeProfil
INSERT ALL
    INTO TypesDeProfil (ProfilId, NomProfil) VALUES (1, 'Healthy')
    INTO TypesDeProfil (ProfilId, NomProfil) VALUES (2, 'Gourmet')
    INTO TypesDeProfil (ProfilId, NomProfil) VALUES (3, 'Parents')
    INTO TypesDeProfil (ProfilId, NomProfil) VALUES (4, 'Pratique')
    INTO TypesDeProfil (ProfilId, NomProfil) VALUES (5, 'Bricolage')
    INTO TypesDeProfil (ProfilId, NomProfil) VALUES (6, 'Eco Friendly')
    INTO TypesDeProfil (ProfilId, NomProfil) VALUES (7, 'Hygiène')
SELECT * FROM dual;



-- Table Appartenir_Type
INSERT ALL
    INTO Appartenir_Type (ClientId, ProfilId) VALUES ('1', 1)
    INTO Appartenir_Type (ClientId, ProfilId) VALUES ('1', 2)
    INTO Appartenir_Type (ClientId, ProfilId) VALUES ('2', 3)
    INTO Appartenir_Type (ClientId, ProfilId) VALUES ('2', 4)
    INTO Appartenir_Type (ClientId, ProfilId) VALUES ('3', 5)
    INTO Appartenir_Type (ClientId, ProfilId) VALUES ('3', 6)
    INTO Appartenir_Type (ClientId, ProfilId) VALUES ('4', 2)
    INTO Appartenir_Type (ClientId, ProfilId) VALUES ('4', 5)
    INTO Appartenir_Type (ClientId, ProfilId) VALUES ('5', 7)
    INTO Appartenir_Type (ClientId, ProfilId) VALUES ('6', 3)
    INTO Appartenir_Type (ClientId, ProfilId) VALUES ('6', 7)
    INTO Appartenir_Type (ClientId, ProfilId) VALUES ('7', 1)
    INTO Appartenir_Type (ClientId, ProfilId) VALUES ('7', 6)
    INTO Appartenir_Type (ClientId, ProfilId) VALUES ('8', 4)
    INTO Appartenir_Type (ClientId, ProfilId) VALUES ('8', 7)
    INTO Appartenir_Type (ClientId, ProfilId) VALUES ('9', 2)
    INTO Appartenir_Type (ClientId, ProfilId) VALUES ('9', 3)
    INTO Appartenir_Type (ClientId, ProfilId) VALUES ('10', 5)
    INTO Appartenir_Type (ClientId, ProfilId) VALUES ('10', 6)
SELECT * FROM dual;



-- Table Stocker
INSERT ALL
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('1', 1, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('1', 2, 0)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('1', 3, 50)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('1', 4, 0)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('1', 5, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('1', 6, 10)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('1', 7, 40)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('1', 8, 0)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('1', 9, 60)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('1', 10, 70)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('2', 1, 15)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('2', 2, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('2', 3, 0)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('2', 4, 40)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('2', 5, 0)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('2', 6, 25)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('2', 7, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('2', 8, 50)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('2', 9, 0)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('2', 10, 20)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('3', 1, 0)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('3', 2, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('3', 3, 0)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('3', 4, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('3', 5, 15)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('3', 6, 10)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('3', 7, 50)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('3', 8, 40)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('3', 9, 0)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('3', 10, 25)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('4', 1, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('4', 2, 7)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('4', 3, 35)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('4', 4, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('4', 5, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('4', 6, 40)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('4', 7, 55)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('4', 8, 3)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('4', 9, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('4', 10, 63)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('5', 1, 29)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('5', 2, 13)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('5', 3, 8)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('5', 4, 50)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('5', 5, 6)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('5', 6, 34)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('5', 7, 44)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('5', 8, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('5', 9, 3)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('5', 10, 25)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('6', 1, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('6', 2, 39)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('6', 3, 0)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('6', 4, 17)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('6', 5, 50)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('6', 6, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('6', 7, 33)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('6', 8, 25)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('6', 9, 11)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('6', 10, 42)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('7', 1, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('7', 2, 29)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('7', 3, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('7', 4, 45)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('7', 5, 21)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('7', 6, 38)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('7', 7, 13)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('7', 8, 0)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('7', 9, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('7', 10, 27)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('8', 1, 35)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('8', 2, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('8', 3, 11)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('8', 4, 42)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('8', 5, 8)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('8', 6, 60)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('8', 7, 14)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('8', 8, 3)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('8', 9, 16)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('8', 10, 54)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('9', 1, 26)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('9', 2, 9)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('9', 3, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('9', 4, 39)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('9', 5, 27)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('9', 6, 34)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('9', 7, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('9', 8, 13)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('9', 9, 2)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('9', 10, 8)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('10', 1, 32)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('10', 2, 14)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('10', 3, 17)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('10', 4, 33)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('10', 5, 27)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('10', 6, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('10', 7, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('10', 8, 16)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('10', 9, 5)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('10', 10, 30)
    
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('11', 1, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('11', 2, 15)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('11', 3, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('11', 4, 10)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('11', 5, 25)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('11', 6, 5)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('11', 7, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('11', 8, 8)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('11', 9, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('11', 10, 20)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('12', 1, 8)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('12', 2, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('12', 3, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('12', 4, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('12', 5, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('12', 6, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('12', 7, 35)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('12', 8, 3)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('12', 9, 26)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('12', 10, 17)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('13', 1, 15)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('13', 2, 24)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('13', 3, 29)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('13', 4, 10)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('13', 5, 40)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('13', 6, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('13', 7, 7)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('13', 8, 31)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('13', 9, 9)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('13', 10, 28)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('14', 1, 27)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('14', 2, 10)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('14', 3, 35)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('14', 4, 25)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('14', 5, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('14', 6, 14)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('14', 7, 8)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('14', 8, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('14', 9, 40)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('14', 10, 6)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('15', 1, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('15', 2, 5)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('15', 3, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('15', 4, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('15', 5, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('15', 6, 17)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('15', 7, 32)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('15', 8, 23)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('15', 9, 9)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('15', 10, 21)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('16', 1, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('16', 2, 7)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('16', 3, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('16', 4, 17)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('16', 5, 40)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('16', 6, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('16', 7, 10)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('16', 8, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('16', 9, 8)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('16', 10, 34)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('17', 1, 6)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('17', 2, 29)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('17', 3, 21)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('17', 4, 33)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('17', 5, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('17', 6, 13)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('17', 7, 25)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('17', 8, 14)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('17', 9, 31)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('17', 10, 22)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('18', 1, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('18', 2, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('18', 3, 7)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('18', 4, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('18', 5, 16)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('18', 6, 11)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('18', 7, 13)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('18', 8, 29)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('18', 9, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('18', 10, 9)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('19', 1, 40)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('19', 2, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('19', 3, 15)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('19', 4, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('19', 5, 6)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('19', 6, 9)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('19', 7, 31)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('19', 8, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('19', 9, 5)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('19', 10, 17)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('20', 1, 16)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('20', 2, 40)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('20', 3, 33)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('20', 4, 8)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('20', 5, 25)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('20', 6, 6)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('20', 7, 13)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('20', 8, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('20', 9, 24)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('20', 10, 10)
    
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('21', 1, 15)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('21', 2, 40)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('21', 3, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('21', 4, 10)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('21', 5, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('21', 6, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('21', 7, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('21', 8, 7)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('21', 9, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('21', 10, 14)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('22', 1, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('22', 2, 14)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('22', 3, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('22', 4, 27)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('22', 5, 8)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('22', 6, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('22', 7, 6)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('22', 8, 16)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('22', 9, 26)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('22', 10, 15)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('23', 1, 8)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('23', 2, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('23', 3, 25)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('23', 4, 16)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('23', 5, 40)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('23', 6, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('23', 7, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('23', 8, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('23', 9, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('23', 10, 22)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('24', 1, 9)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('24', 2, 35)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('24', 3, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('24', 4, 27)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('24', 5, 14)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('24', 6, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('24', 7, 31)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('24', 8, 8)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('24', 9, 40)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('24', 10, 6)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('25', 1, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('25', 2, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('25', 3, 16)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('25', 4, 9)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('25', 5, 31)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('25', 6, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('25', 7, 24)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('25', 8, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('25', 9, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('25', 10, 23)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('26', 1, 16)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('26', 2, 27)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('26', 3, 32)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('26', 4, 6)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('26', 5, 24)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('26', 6, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('26', 7, 8)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('26', 8, 17)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('26', 9, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('26', 10, 10)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('27', 1, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('27', 2, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('27', 3, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('27', 4, 17)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('27', 5, 23)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('27', 6, 31)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('27', 7, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('27', 8, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('27', 9, 25)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('27', 10, 10)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('28', 1, 7)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('28', 2, 26)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('28', 3, 16)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('28', 4, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('28', 5, 13)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('28', 6, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('28', 7, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('28', 8, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('28', 9, 8)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('28', 10, 15)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('29', 1, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('29', 2, 31)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('29', 3, 14)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('29', 4, 8)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('29', 5, 26)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('29', 6, 10)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('29', 7, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('29', 8, 14)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('29', 9, 24)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('29', 10, 12)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('30', 1, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('30', 2, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('30', 3, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('30', 4, 10)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('30', 5, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('30', 6, 35)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('30', 7, 6)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('30', 8, 15)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('30', 9, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('30', 10, 23)
    
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('31', 1, 25)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('31', 2, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('31', 3, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('31', 4, 29)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('31', 5, 21)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('31', 6, 37)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('31', 7, 15)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('31', 8, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('31', 9, 32)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('31', 10, 23)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('32', 1, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('32', 2, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('32', 3, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('32', 4, 10)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('32', 5, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('32', 6, 24)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('32', 7, 36)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('32', 8, 14)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('32', 9, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('32', 10, 27)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('33', 1, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('33', 2, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('33', 3, 35)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('33', 4, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('33', 5, 17)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('33', 6, 29)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('33', 7, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('33', 8, 24)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('33', 9, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('33', 10, 30)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('34', 1, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('34', 2, 14)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('34', 3, 26)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('34', 4, 31)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('34', 5, 9)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('34', 6, 24)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('34', 7, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('34', 8, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('34', 9, 33)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('34', 10, 12)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('35', 1, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('35', 2, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('35', 3, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('35', 4, 27)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('35', 5, 15)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('35', 6, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('35', 7, 25)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('35', 8, 35)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('35', 9, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('35', 10, 40)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('36', 1, 13)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('36', 2, 24)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('36', 3, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('36', 4, 15)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('36', 5, 32)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('36', 6, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('36', 7, 40)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('36', 8, 14)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('36', 9, 10)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('36', 10, 30)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('37', 1, 21)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('37', 2, 16)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('37', 3, 25)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('37', 4, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('37', 5, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('37', 6, 35)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('37', 7, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('37', 8, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('37', 9, 26)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('37', 10, 17)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('38', 1, 27)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('38', 2, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('38', 3, 21)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('38', 4, 15)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('38', 5, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('38', 6, 32)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('38', 7, 9)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('38', 8, 40)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('38', 9, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('38', 10, 28)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('39', 1, 31)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('39', 2, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('39', 3, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('39', 4, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('39', 5, 40)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('39', 6, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('39', 7, 15)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('39', 8, 27)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('39', 9, 32)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('39', 10, 12)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('40', 1, 16)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('40', 2, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('40', 3, 40)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('40', 4, 13)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('40', 5, 23)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('40', 6, 26)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('40', 7, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('40', 8, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('40', 9, 35)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('40', 10, 30)

    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('41', 1, 35)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('41', 2, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('41', 3, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('41', 4, 15)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('41', 5, 40)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('41', 6, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('41', 7, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('41', 8, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('41', 9, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('41', 10, 30)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('42', 1, 25)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('42', 2, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('42', 3, 14)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('42', 4, 10)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('42', 5, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('42', 6, 26)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('42', 7, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('42', 8, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('42', 9, 17)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('42', 10, 28)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('43', 1, 23)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('43', 2, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('43', 3, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('43', 4, 14)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('43', 5, 26)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('43', 6, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('43', 7, 25)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('43', 8, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('43', 9, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('43', 10, 35)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('44', 1, 21)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('44', 2, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('44', 3, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('44', 4, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('44', 5, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('44', 6, 35)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('44', 7, 27)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('44', 8, 14)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('44', 9, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('44', 10, 30)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('45', 1, 26)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('45', 2, 15)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('45', 3, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('45', 4, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('45', 5, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('45', 6, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('45', 7, 25)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('45', 8, 17)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('45', 9, 24)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('45', 10, 20)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('46', 1, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('46', 2, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('46', 3, 26)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('46', 4, 13)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('46', 5, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('46', 6, 35)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('46', 7, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('46', 8, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('46', 9, 25)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('46', 10, 10)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('47', 1, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('47', 2, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('47', 3, 24)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('47', 4, 19)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('47', 5, 27)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('47', 6, 23)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('47', 7, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('47', 8, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('47', 9, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('47', 10, 40)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('48', 1, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('48', 2, 15)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('48', 3, 12)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('48', 4, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('48', 5, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('48', 6, 25)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('48', 7, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('48', 8, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('48', 9, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('48', 10, 30)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('49', 1, 14)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('49', 2, 20)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('49', 3, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('49', 4, 25)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('49', 5, 35)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('49', 6, 16)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('49', 7, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('49', 8, 32)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('49', 9, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('49', 10, 20)
    --
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('50', 1, 30)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('50', 2, 22)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('50', 3, 18)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('50', 4, 25)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('50', 5, 35)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('50', 6, 14)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('50', 7, 28)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('50', 8, 32)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('50', 9, 16)
    INTO Stocker (ProduitId, MagId, QteStock) VALUES ('50', 10, 25)
SELECT * FROM dual;